// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUlpyO4pFbQUVe0vrEjeFznF0MdGr1Uk',
    appId: '1:849070516772:web:c952ef813f25bdc19286b1',
    messagingSenderId: '849070516772',
    projectId: 'picnic-search',
    authDomain: 'picnic-search.firebaseapp.com',
    storageBucket: 'picnic-search.firebasestorage.app',
    measurementId: 'G-0SST2X4RZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMveCNOaCqjoH3zhFiOKz3EHLZnaeL04',
    appId: '1:849070516772:android:dc6865dd981c05db9286b1',
    messagingSenderId: '849070516772',
    projectId: 'picnic-search',
    storageBucket: 'picnic-search.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_V84ZNmXDWqmENypKNBpwvvJcbezf1WQ',
    appId: '1:849070516772:ios:80951a40fa984bd99286b1',
    messagingSenderId: '849070516772',
    projectId: 'picnic-search',
    storageBucket: 'picnic-search.firebasestorage.app',
    iosBundleId: 'com.example.picnicSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_V84ZNmXDWqmENypKNBpwvvJcbezf1WQ',
    appId: '1:849070516772:ios:80951a40fa984bd99286b1',
    messagingSenderId: '849070516772',
    projectId: 'picnic-search',
    storageBucket: 'picnic-search.firebasestorage.app',
    iosBundleId: 'com.example.picnicSearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDUlpyO4pFbQUVe0vrEjeFznF0MdGr1Uk',
    appId: '1:849070516772:web:1554ae55ab04da529286b1',
    messagingSenderId: '849070516772',
    projectId: 'picnic-search',
    authDomain: 'picnic-search.firebaseapp.com',
    storageBucket: 'picnic-search.firebasestorage.app',
    measurementId: 'G-53RDKYY6Y7',
  );
}
